apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: input-binding
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 5s" # a valid cron schedule
