apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: output-binding
spec:
  type: bindings.postgres
  version: v1
  metadata:
  - name: url
    value: "postgresql://dapr:secret@localhost/orders" # Connection String
